POST   http://localhost:3000/api/cursos/programacion HTTP/1.1
Content-Type: application/json

{           
    "id": 4,
    "titulo": "Aprende react.js",
    "lenguaje": "react.js", 
    "vistas": 104673,
    "nivel": "intermedio"
}


###
PUT http://localhost:3000/api/cursos/programacion/4 HTTP/1.1
Content-Type: application/json

{           
    "id": 4,
    "titulo": "Python intermedio con proyectos",
    "lenguaje": "python.js", 
    "vistas": 414113,
    "nivel": "intermedio"
}



###
PATCH http://localhost:3000/api/cursos/programacion/4 HTTP/1.1
Content-Type: application/json

{
    "titulo": "Python basico con proyectos",
    "vistas": 9434113
}


###
DELETE http://localhost:3000/api/cursos/programacion/3 HTTP/1.1
